### ISSUE TITLE
Configure Countdown.js

### ISSUE THREAD

**Issue by sandro-gutierrez** [epiksel/countdown#5]
Hello my name is Sandro. I'm a end user. I bought a full template on Themeforest http://preview.themeforest.net/item/event-event-conference-html-template/full_screen_preview/19070769 

This template use your countdown.js. I need to set up the end date, so your function can calculate the exact mount of days, hours, minutes and seconds. Can you explain to me where i can set up this?

Thanks very much.
Best regards

Sandro

**Comment by ekavando** [comment]
Hi Sandro,
Please look usage example: http://epiksel.github.io/countdown

Best regards
